services:
  app:
    ports: !reset []
    environment:
      NODE_ENV: production
      COOKIE_SECURE: "true"
      MINIO_PUBLIC_URL: https://media.nguyengiakhoi.io.vn
      FRONTEND_URL: https://api.nguyengiakhoi.io.vn
      CLIENT_URL: https://api.nguyengiakhoi.io.vn
    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      - traefik.http.routers.globetrek.rule=Host(`api.nguyengiakhoi.io.vn`)
      - traefik.http.routers.globetrek.entrypoints=web
      - traefik.http.services.globetrek.loadbalancer.server.port=8081

  minio:
    ports: !reset []
    environment:
      MINIO_SERVER_URL: https://media.nguyengiakhoi.io.vn
    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      - traefik.http.routers.globetrek-media.rule=Host(`media.nguyengiakhoi.io.vn`)
      - traefik.http.routers.globetrek-media.entrypoints=web
      - traefik.http.services.globetrek-media.loadbalancer.server.port=9000

networks:
  traefik-net:
    external: true
